spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  security:
    jwt:
      secret-key: secret-key-local
      expires-in: 108000

logging:
  level:
    com.lucasmoraist: DEBUG

app:
  security-ignore:
    apiV1: /api/v1/**
  allowed-origins:
    - http://localhost:3000